### ISSUE TITLE
Syntax error macroexpanding clojure.core/ns at (base64_vlq.clj:1:1).

### ISSUE THREAD

**Issue by farzana-tarannum** [nrepl/piggieback#103]
Hello I am getting following error - 

input - 

clj -A:reble

[Rebel readline] Type :repl/help for online help info
user=> (require 'cider.piggieback)

output:

WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: cljs.util, being replaced by: #'cljs.util/boolean?
Syntax error macroexpanding clojure.core/ns at (base64_vlq.clj:1:1).
((require [clojure.string :as string] [cljs.source-map.base64 :as base64])) - failed: Extra input spec: :clojure.core.specs.alpha/ns-form

my deps.edn is - 

{:deps
 {clj-time {:mvn/version "0.14.2"}
  nrepl {:mvn/version "0.6.0"}
  cider/piggieback {:mvn/version "0.4.1-SNAPSHOT"}}
 :aliases {:reble {:extra-deps {:com.bhauman/rebel-readline {:mvn/version "0.1.4"}}
                   :main-opts ["-m" "rebel-readline.main"]}}}

My devs environment:

Linux arch 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux

tools.deps versio: linux-install-1.10.0.414.sh

I have tried with cider/piggieback  0.4.0 and getting same error.

**Comment by SevereOverfl0w** [comment]
Looks like a :require vs require in base64_vlq.clj but I'm not sure what that is.

**Comment by cichli** [comment]
This was fixed in clojure/clojurescript@48b83d900dc46e912fcefc2365f806f5c8c15dfe – could you try upgrading your ClojureScript version?

**Comment by farzana-tarannum** [comment]
thanks, fixed after updating clojuresript to lastest version.
