### ISSUE TITLE
No such namespace: cljs.repl.node exception

### ISSUE THREAD

**Issue by sblask** [nrepl/piggieback#116]
I am trying to follow the instructions from the README, but I get an exception:
```
cljs.user=> (require 'cljs.repl.node)
Unexpected error (ExceptionInfo) compiling at (<cljs repl>:1:1).
No such namespace: cljs.repl.node, could not locate cljs/repl/node.cljs, cljs/repl/node.cljc, or JavaScript source providing "cljs.repl.node" at line 1 <cljs repl>
```
I have no idea whether it's me or piggieback and how to fix it.

**Comment by bbatsov** [comment]
You've installed Node.js beforehand, right?

**Comment by sblask** [comment]
Yes:
```
$ node -v
v13.13.0
```

**Comment by bbatsov** [comment]
Btw, I've noticed in your example you're already in a ClojureScript REPL, so this might be the problem. You're supposed to run this code in a Clojure REPL to switch it to ClojureScript.

**Comment by sblask** [comment]
Sorry about that. Clojure is all new to me, but I am working on an existing project. Sure enough there was this in the config:

```
            "repl"           [["with-profile" "+repl"]
                              ["run" "--attach" "7888" "--custom-help" "\"\"" "-e" "(figwheel-sidecar.repl-api/cljs-repl \"main\")"]]

```

Once I had it removed the require worked as documented.
