### ISSUE TITLE
Can't find clojurescript repl-env classes?

### ISSUE THREAD

**Issue by didibus** [nrepl/piggieback#89]
I've got a project.clj file as such:

```
(defproject cljs-playground "0.1.0-SNAPSHOT"
  :dependencies [[cider/piggieback "0.3.6"]
                 [nrepl "0.4.1"]]
  :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]})
```

And when I run `lein repl` and type in: `(cider.piggieback/cljs-repl (cljs.repl.nashorn/repl-env))` I get:

```
CompilerException java.lang.ClassNotFoundException: cljs.repl.nashorn, compiling:(/tmp/form-init627831113088014825.clj:1:29)
```

I'm kind of baffled. How come that namespace is missing?

I also tried adding clojurescript directly to no avail.

**Comment by bbatsov** [comment]
@didibus Leiningen doesn't support yet nREPL >= 0.3, which is the cause of your problem.
